---
mq_domain: galaxy-mq-dev.dev.ifb.local

nginx_servers:
  - galaxy-mq-dev
nginx_ssl_servers:
  - galaxy-mq-dev-ssl
nginx_ssl_role: galaxyproject.self_signed_certs
openssl_domains:
  - "{{ mq_domain }}"
openssl_self_sign: true # ADD THIS

nginx_conf_ssl_certificate_key: /etc/ssl/private/{{ openssl_domains[0] }}.pem
nginx_conf_ssl_certificate: /etc/ssl/certs/{{ openssl_domains[0] }}.crt
#Install pip docker package for ansible
pip_install_packages:
  - name: docker

# RabbitMQ
rabbitmq_container:
  name: rabbit_hole
  image: rabbitmq:3.11-management
  hostname: "{{ mq_domain }}"

rabbitmq_plugins:
  - rabbitmq_management

rabbitmq_config:
  listeners:
    tcp: none
  ssl_listeners:
    default: 5671
  ssl_options:
    verify: verify_none
    cacertfile: /etc/ssl/private/{{ openssl_domains[0] }}.csr
    certfile: /etc/ssl/certs/{{ openssl_domains[0] }}.crt
    keyfile: /etc/ssl/private/{{ openssl_domains[0] }}.pem
    fail_if_no_peer_cert: 'false'

  management_agent:
    disable_metrics_collector: "false"
  management:
    disable_stats: 'false'
  consumer_timeout: 21600000 # 6 hours in milliseconds

rabbitmq_vhosts:
  - /pulsar/pulsar_fr02

rabbitmq_users:
  - user: mqadmin
    password: "{{ vault_rabbitmq_admin_password }}"
    tags: administrator
    vhost: /
  - user: pulsar_fr02
    password: "{{ vault_rabbitmq_password_vhost }}"
    vhost: /pulsar/pulsar_fr02
