# RabbitMQ for Pulsar
- src: geerlingguy.docker
  version: 4.1.1
- src: usegalaxy_eu.rabbitmqserver
  version: 1.4.4
- src: usegalaxy_eu.certbot
  version: 0.1.11
- src: galaxyproject.nginx
  version: 0.7.1