# RabbitMQ for Pulsar
- src: geerlingguy.docker
  version: 4.1.1
- src: usegalaxy_eu.rabbitmqserver
  version: 1.4.4
- name: usegalaxy_eu.certbot
  version: 0.1.5
- src: galaxyproject.nginx
  version: 3.1.4
- src: usegalaxy_eu.htcondor
  version: 2.2.0
- src: galaxyproject.pulsar
  version: 1.0.1