# RabbitMQ for Pulsar
- src: geerlingguy.docker
  version: 4.1.1
- src: usegalaxy_eu.rabbitmqserver
  version: 1.4.4
- src: galaxyproject.self_signed_certs
  version: 0.0.3
- src: galaxyproject.nginx
  version: 0.7.1